<a href="https://colab.research.google.com/github/Luanffca/Machine-Learning/blob/main/Previsao_Cliente.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
# Conctando ou drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [28]:
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/clientes.csv')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_cliente                100000 non-null  int64
 1   mes                       100000 non-null  int64
 2   idade                     100000 non-null  float64
 3   profissao                 100000 non-null  object
 4   salario_anual             100000 non-null  float64
 5   num_contas                100000 non-null  float64
 6   num_cartoes               100000 non-null  float64
 7   juros_emprestimo          100000 non-null  float64
 8   num_emprestimos           100000 non-null  float64
 9   dias_atraso               100000 non-null  float64
 10  num_pagamentos_atrasados  100000 non-null  float64
 11  num_verificacoes_credito  100000 non-null  float64
 12  mix_credito               100000 non-null  object
 13  divida_total              100000 non-null  float64
 14  taxa_uso_credito          100000 non-null  float64
 15  idade_historico_credito   100000 non-null  float64
 16  investimento_mensal       100000 non-null  float64
 17  comportamento_pagamento   100000 non-null  object
 18  saldo_final_mes           100000 non-null  float64
 19  score_credito             100000 non-null  object
 20  emprestimo_carro          100000 non-null  int64
 21  emprestimo_casa           100000 non-null  int64
 22  emprestimo_pessoal        100000 non-null  int64
 23  emprestimo_credito        100000 non-null  int64
 24  emprestimo_estudantil     100000 non-null  int64
dtypes: float64(14), int64(7), object(4)
memory usage: 19.1+ MB
None

In [29]:
from sklearn.preprocessing import LabelEncoder

In [30]:
codificador = LabelEncoder()
df['profissao'] = codificador.fit_transform(df['profissao'])
df['mix_credito'] = codificador.fit_transform(df['mix_credito'])
df['comportamento_pagamento'] = codificador.fit_transform(df['comportamento_pagamento'])
df

,id_cliente,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,...,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,score_credito,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,3392,1,23.0,2,19114.12,3.0,4.0,3.0,4.0,3.0,...,265.0,21.465380,1,312.494089,Good,1,1,1,1,0
1,3392,2,23.0,2,19114.12,3.0,4.0,3.0,4.0,3.0,...,266.0,21.465380,3,284.629162,Good,1,1,1,1,0
2,3392,3,23.0,2,19114.12,3.0,4.0,3.0,4.0,3.0,...,267.0,21.465380,5,331.209863,Good,1,1,1,1,0
3,3392,4,23.0,2,19114.12,3.0,4.0,3.0,4.0,5.0,...,268.0,21.465380,4,223.451310,Good,1,1,1,1,0
4,3392,5,23.0,2,19114.12,3.0,4.0,3.0,4.0,6.0,...,269.0,21.465380,2,341.489231,Good,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,37932,4,25.0,11,39628.99,4.0,6.0,7.0,2.0,23.0,...,378.0,24.028477,0,479.866228,Poor,1,0,0,0,1
99996,37932,5,25.0,11,39628.99,4.0,6.0,7.0,2.0,18.0,...,379.0,24.028477,2,496.651610,Poor,1,0,0,0,1
99997,37932,6,25.0,11,39628.99,4.0,6.0,7.0,2.0,27.0,...,380.0,24.028477,0,516.809083,Poor,1,0,0,0,1
99998,37932,7,25.0,11,39628.99,4.0,6.0,7.0,2.0,20.0,...,381.0,24.028477,3,319.164979,Standard,1,0,0,0,1
99999,37932,8,25.0,11,39628.99,4.0,6.0,7.0,2.0,18.0,...,382.0,24.028477,2,393.673696,Poor,1,0,0,0,1

In [31]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_cliente                100000 non-null  int64
 1   mes                       100000 non-null  int64
 2   idade                     100000 non-null  float64
 3   profissao                 100000 non-null  int64
 4   salario_anual             100000 non-null  float64
 5   num_contas                100000 non-null  float64
 6   num_cartoes               100000 non-null  float64
 7   juros_emprestimo          100000 non-null  float64
 8   num_emprestimos           100000 non-null  float64
 9   dias_atraso               100000 non-null  float64
 10  num_pagamentos_atrasados  100000 non-null  float64
 11  num_verificacoes_credito  100000 non-null  float64
 12  mix_credito               100000 non-null  int64
 13  divida_total              100000 non-null  float64
 14  taxa_uso_credito          100000 non-null  float64
 15  idade_historico_credito   100000 non-null  float64
 16  investimento_mensal       100000 non-null  float64
 17  comportamento_pagamento   100000 non-null  int64
 18  saldo_final_mes           100000 non-null  float64
 19  score_credito             100000 non-null  object
 20  emprestimo_carro          100000 non-null  int64
 21  emprestimo_casa           100000 non-null  int64
 22  emprestimo_pessoal        100000 non-null  int64
 23  emprestimo_credito        100000 non-null  int64
 24  emprestimo_estudantil     100000 non-null  int64
dtypes: float64(14), int64(10), object(1)
memory usage: 19.1+ MB
None

In [32]:
y = df['score_credito']
x = df.drop(['score_credito', 'id_cliente'], axis=1)

from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(x,y, test_size=0.3, random_state=1)

In [33]:
# Criando o modelo de IA -> Score de credito: Ruim, Medio, Bom
# Modelo de Arvore de Decisao

from sklearn.ensemble import RandomForestClassifier
modelo_arvoredecisao = RandomForestClassifier()
modelo_arvoredecisao.fit(x_treino, y_treino)

RandomForestClassifier()

In [34]:
# KNN - nearest neighbords
from sklearn.neighbors import KNeighborsClassifier
modelo_KNN = KNeighborsClassifier()
modelo_KNN.fit(x_treino, y_treino)

KNeighborsClassifier()

In [40]:
# Acuracia dos modelos

from sklearn.metrics import accuracy_score

previsao_arvoredecissao = modelo_arvoredecisao.predict(x_teste)
previsao_knn = modelo_KNN.predict(x_teste)

In [41]:
print("{:.2f}% modelo -> árvore de decisão".format(accuracy_score(y_teste, previsao_arvoredecissao)*100))
print("{:.2f}% modelo -> KNN".format(accuracy_score(y_teste, previsao_knn)*100))

82.51% modelo -> árvore de decisão
73.24% modelo -> KNN

In [46]:
novos_clientes = pd.read_csv('/content/drive/My Drive/Colab Notebooks/novos_clientes.csv')
print(novos_clientes.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   mes                       3 non-null      int64
 1   idade                     3 non-null      float64
 2   profissao                 3 non-null      object
 3   salario_anual             3 non-null      float64
 4   num_contas                3 non-null      float64
 5   num_cartoes               3 non-null      float64
 6   juros_emprestimo          3 non-null      float64
 7   num_emprestimos           3 non-null      float64
 8   dias_atraso               3 non-null      float64
 9   num_pagamentos_atrasados  3 non-null      float64
 10  num_verificacoes_credito  3 non-null      float64
 11  mix_credito               3 non-null      object
 12  divida_total              3 non-null      float64
 13  taxa_uso_credito          3 non-null      float64
 14  idade_historico_credito   3 non-null      float64
 15  investimento_mensal       3 non-null      float64
 16  comportamento_pagamento   3 non-null      object
 17  saldo_final_mes           3 non-null      float64
 18  emprestimo_carro          3 non-null      int64
 19  emprestimo_casa           3 non-null      int64
 20  emprestimo_pessoal        3 non-null      int64
 21  emprestimo_credito        3 non-null      int64
 22  emprestimo_estudantil     3 non-null      int64
dtypes: float64(14), int64(6), object(3)
memory usage: 680.0+ bytes
None

In [47]:
codificador = LabelEncoder()
novos_clientes['profissao'] = codificador.fit_transform(novos_clientes['profissao'])
novos_clientes['mix_credito'] = codificador.fit_transform(novos_clientes['mix_credito'])
novos_clientes['comportamento_pagamento'] = codificador.fit_transform(novos_clientes['comportamento_pagamento'])
print(novos_clientes.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   mes                       3 non-null      int64
 1   idade                     3 non-null      float64
 2   profissao                 3 non-null      int64
 3   salario_anual             3 non-null      float64
 4   num_contas                3 non-null      float64
 5   num_cartoes               3 non-null      float64
 6   juros_emprestimo          3 non-null      float64
 7   num_emprestimos           3 non-null      float64
 8   dias_atraso               3 non-null      float64
 9   num_pagamentos_atrasados  3 non-null      float64
 10  num_verificacoes_credito  3 non-null      float64
 11  mix_credito               3 non-null      int64
 12  divida_total              3 non-null      float64
 13  taxa_uso_credito          3 non-null      float64
 14  idade_historico_credito   3 non-null      float64
 15  investimento_mensal       3 non-null      float64
 16  comportamento_pagamento   3 non-null      int64
 17  saldo_final_mes           3 non-null      float64
 18  emprestimo_carro          3 non-null      int64
 19  emprestimo_casa           3 non-null      int64
 20  emprestimo_pessoal        3 non-null      int64
 21  emprestimo_credito        3 non-null      int64
 22  emprestimo_estudantil     3 non-null      int64
dtypes: float64(14), int64(9)
memory usage: 680.0 bytes
None

In [49]:
previsao = modelo_arvoredecisao.predict(novos_clientes)
print(previsao)

['Poor' 'Good' 'Standard']